cituao_academico_homepage:
    path:  /academico
    defaults: { _controller: CituaoAcademicoBundle:Default:index }

cituao_academico_actualizar:
    path:  /academico/actualizar
    defaults: { _controller: CituaoAcademicoBundle:Default:actualizar }

cituao_academico_practicantes:
    path:  /academico/practicantes
    defaults: { _controller: CituaoAcademicoBundle:Default:practicantes }

cituao_academico_cronograma:
    path:  /academico/cronograma/{id}
    defaults: { _controller: CituaoAcademicoBundle:Default:cronograma }

cituao_academico_registrar_asesoria:
    path:  /academico/entregarasesoria/practicante={id}&asesoria={numase}
    defaults: { _controller: CituaoAcademicoBundle:Default:registrarAsesoria }

cituao_academico_consultar_asesoria:
    path:  /academico/consultarasesoria/practicante={id}&asesoria={numase}
    defaults: { _controller: CituaoAcademicoBundle:Default:consultarAsesoria }

cituao_academico_registrar_visitap:
    path:  /academico/registrarp/practicante={id}
    defaults: { _controller: CituaoAcademicoBundle:Default:registrarVisitap }

cituao_academico_registrar_comentario:
    path:  /academico/registrarcomentario/practicante={id}&evaluacion={numeva}
    defaults: { _controller: CituaoAcademicoBundle:Default:registrarComentario }

cituao_academico_registrar_cualicuanti:
    path:  /academico/registrarcualicuanti/practicante={id}&cuali={numcua}
    defaults: { _controller: CituaoAcademicoBundle:Default:registrarCualicuanti }

cituao_academico_registrar_informefinal:
    path:  /academico/registrarinformefinal/practicante={id}
    defaults: { _controller: CituaoAcademicoBundle:Default:registrarInformafinal }

cituao_academico_verasesorexterno:
    path:  /academico/asesorexterno/externo={id}
    defaults: { _controller: CituaoAcademicoBundle:Default:verasesorExterno }

