cituao_practicante_homepage:
    path:  /practicante
    defaults: { _controller: CituaoPracticanteBundle:Default:index }

cituao_practicante_mihojadevida:
    path:  /practicante/mihojadevida
    defaults: { _controller: CituaoPracticanteBundle:Default:hojadevida }

cituao_practicante_cronograma:
    path:  /practicante/cronograma
    defaults: { _controller: CituaoPracticanteBundle:Default:cronograma }

cituao_practicante_registrar_asesoria:
    path:  /practicante/registrarasesoria/practicante={id}&asesoria={numase}
    defaults: { _controller: CituaoPracticanteBundle:Default:registrarAsesoria }

cituao_practicante_registrar_cualicuanti:
    path:  /practicante/registrarcualicuanti/practicante={id}&cualicuanti={numcua}
    defaults: { _controller: CituaoPracticanteBundle:Default:registrarCualicuanti }
    
cituao_practicante_ver_asesoracademico:
    path:  /practicante/mi-asesor-academico
    defaults: { _controller: CituaoPracticanteBundle:Default:verasesorAcademico }
    
cituao_practicante_ver_asesorexterno:
    path:  /practicante/mi-asesor-externo
    defaults: { _controller: CituaoPracticanteBundle:Default:verasesorExterno }
 
cituao_practicante_ver_centro:
    path:  /practicante/mi-centro
    defaults: { _controller: CituaoPracticanteBundle:Default:verCentro }

cituao_practicante_registrar_informefinal:
    path:  /practicante/mi-informe-final/practicante={id}
    defaults: { _controller: CituaoPracticanteBundle:Default:registrarInformefinal }

cituao_practicante_subir_proyecto:
    path:  /practicante/subir-proyecto
    defaults: { _controller: CituaoPracticanteBundle:Default:subirProyecto }
    
cituao_practicante_registrar_compromiso:
    path:  /practicante/registrar-compromiso/practicante={id}&evaluacion={numeva}
    defaults: { _controller: CituaoPracticanteBundle:Default:registrarCompromiso }
